branches:
  only:
  - master
cache: bundler
language: ruby
services:
  - postgresql
rvm:
  - 2.7.1
env:
  - DATABASE_URL=postgres://postgres@127.0.0.1:5432/train-spanish-test SECRET_TOKEN=abcdefabcdefabcdef
before_install:
  - gem install bundler
  - nvm install node
  - npm i -g yarn
before_script:
  - yarn
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rails webpacker:compile
script:
  - bundle exec bundler-audit update && bundle exec bundler-audit check
  - bundle exec rubocop
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: dsizzbulkOORfQjBboNRgSezSvxoWXom/Ve/gFHx63TpqaSXQ/dGAUkGpiGtBSMB8x7yz9Kr9i8Uk7/sK+gv3pHcxzAzYs2KnDb69MoamTafmScMutgxxuT8NiOkZQQecibgX8ox496eXKWiXD6MzkDziue1Ya41bOd/GjM9vnbwIt/AaYtAOgoyW22wOe7JtPkhUCCpGVj+In6PF9Vko8lffgBuD8Q1qVsm59eOg3PRkjFdPmgBADlJc6Y+WC3IauAgEpkoqMGjSAeA3tOLuFMLxJbGc8JI/zs6VFFb8nE9gRd/BeN3aJhLT7MYmVYWsxc9UMk8mzWnPBQlJVwhFaR5PYfthp9Xl4hLO7CaMTVRZoAasfXNPx/CailPvXRnZLEMaUWR9dTIWWB5/7ZPEY9oVBzG12zh+CaFBvXhcun29oQ8ZYFTNMlDmpXkm/iakBrLTt6rTEPuIOtSP1aHXSGVcO8Zm3pf4OUF81gney/b6eiCnbS6psXzDAY5DOCXdWdSPHDWLkvl9ehAWweXaKHf2AOnZxYkQRM4RHx6MIdYjRRYgR1QfuScwkdbk9lOdBmZTsSTgBOoZlcvXmtTjR1oIjTPBX0SHrT0bMQ1IGw23sKYqy9zWkzncOO8Ass0qWPhPNxTizzlP6dLz0Nv3kn6tEFXLSDJbwQWawSpg3M=
  app: train-spanish
  on:
    repo: am-dmr/train-spanish
  run:
    - "rake db:migrate"
